### PR TITLE
chore: upgrade version to 2.0.0

### PR DESCRIPTION
**Pull request by keithamus**
For a smooth migration this should be a major version bump.

### CODE REVIEW

**Comment by trygve-lie** [comment]
Great. Are you able to give me access to the module on NPM? I use semantic release here so I would like to set up a NPM publish key before I merge this one (which will be the first publish).

**Comment by keithamus** [comment]
What's your npm username?

**Comment by trygve-lie** [comment]
Its `trygve`. https://www.npmjs.com/~trygve

**Comment by keithamus** [comment]
Added you to the npm package.

**Comment by trygve-lie** [comment]
Thanks a lot :) I've set up a publish token in NPM and added it to this repo so publish should now happen through the publish action when I merge this.

**Comment by trygve-lie** [comment]
A bit of juggling but now out in v2.0.0: https://github.com/trygve-lie/rollup-plugin-import-map/releases/tag/v2.0.0 :tada:

**Pull request merged**
